### ISSUE TITLE
urlToken is not recognized

### ISSUE THREAD

**Issue by zane-commeatio** [jon-sully/react-netlify-identity-gotrue#10]
I have trouble to handle the email confirmation process, when i click on the link it redirect me on `https://<HOSTNAME>/#confirmation_token=-NyLBWtTFqpsJW7ge0AMHw`
and the confirmation process is triggered. 
BUT i'm not able to catch if the urlToken is here because when i 
```js
useEffect(() => {
    console.log(identity.urlToken)
    if (identity.urlToken?.type === "confirmation") {
	    toast({
		    title: "Email confirmé !",
		    status: "success",
		    position: "top",
		    duration: 7000,
		    isClosable: true,
	    })
    }
}, [])
```
on the index page (so no prior component have acces to identity) it is always `undefined`.

**Comment by jon-sully** [comment]
The confirmation process is handled automatically — It's not something you can hook into at this point

**Comment by zane-commeatio** [comment]
So there is no way to show a spinner while the confirmation process in going and a success message when it respond ok ?

**Comment by jon-sully** [comment]
Ah, I'm sorry — been a while since I've hopped into this project. Docs note that checking 

```js
identity.urlToken?.type === "confirmation"
```

_is_ the correct way to flag for a spinner to show while the confirmation process (which is automatic) is running, but the confirmation process may run fast enough that React doesn't actually update that state to show like you think. E.g. the confirmation request may run so quick that the UI never shows a spinner (and in your case above, the `toast()` call would never run). So the `urlToken.type === "confirmation"` check should only ever be used for _UI_ concerns (showing a spinner) and not for functionality / analytics concerns since it may get skipped in fast-running confirmations.

As [shown in the Gatsby Demo project](https://github.com/jon-sully/gatsby-plugin-netlify-identity-gotrue-demo/blob/c4b6dfb42197bdb18f908a5fbab4e06e2dd3bfed/src/components/AuthOverlay.jsx#L39), the overlay / spinner is shown any time `urlToken.type === "confirmation"`. If the `urlToken.type` is set to `"confirmation"`, it's processing (in real time) and the spinner can be shown. The library will automatically change `urlToken` to `null` once the processing is done. So using JSX like 

```jsx
{identity.urlToken?.type === "confirmation" &&
  <p>Confirming User...</p>
}
```

Is perfectly valid

**Comment by zane-commeatio** [comment]
Yeah i am using it only for UI but when i log identity.urlToken its always undefined so the ui never display the spinner (or the toast)
